name = "CodingTheory"
uuid = "7ca085cf-10e4-43da-ad7d-8f62f68877b3"
authors = ["Eric Sabo <esabo3@gatech.edu>",
           "Ben Ide <ben@bencide.com>"]
version = "0.1.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
