name: Documentation

on:
  push:
    branches:
      - master
      - subsystem
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.9'
      - uses: julia-actions/cache@v1
        with:
          cache-name: subsystem-docs
          # WARNING: cache-registries is actually slower for Windows runners
          cache-registries: "true"
          # WARNING: cache-compiled can break with certain choices of OS and architecture.
          # see https://github.com/julia-actions/cache/issues/11
          cache-compiled: "true"
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop([PackageSpec(url="https://github.com/esabo/RamanujanGraphs.jl"), PackageSpec(path=pwd())]); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.Docs }}
        run: julia --project=docs/ docs/make.jl
      #   run: julia --project=docs/ --code-coverage=user docs/make.jl
      # - uses: julia-actions/julia-processcoverage@v1
      # - uses: codecov/codecov-action@v1
